# CoffeeNChill Azurite - local Azure Storage emulator
# Build: docker build -t <dockerhub_username>/coffeenchill-Azurite:v1.0 .
# Run:   docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 <dockerhub_username>/coffeenchill-Azurite:v1.0

FROM mcr.microsoft.com/azure-storage/azurite
EXPOSE 10000 10001 10002
